version: '3.7'
services:
  allure-server:
    # For local debug #
    build: .
    # image: pacoke/allure-server:2.13.6
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./ext:/ext:rw
      - ./allure-server-store:/allure:rw
    restart: unless-stopped
    depends_on:
      - postgres
      - datadog-agent

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    env_file:
      - .env
    environment:
      DD_SITE: ${DD_SITE:-datadoghq.eu}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: 'true'
      DD_DOGSTATSD_METRICS_STATS_ENABLE: 'true'
      DD_APM_ENABLED: 'false'
      DD_LOGS_ENABLED: 'false'
    ports:
      - 8125:8125/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  postgres:
    image: postgres:16.3-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./allure-server-store-db:/var/lib/postgresql/data:rw
